// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhGoe2UuSCVuSd6g7UqbSgEyJbB6mzOGE',
    appId: '1:523719868125:web:5e6db4fd34ff9091026534',
    messagingSenderId: '523719868125',
    projectId: 'blooddonation-f9c79',
    authDomain: 'blooddonation-f9c79.firebaseapp.com',
    storageBucket: 'blooddonation-f9c79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCytOPmy26ZwR2G11DY8Wi93U_P7C5mv4w',
    appId: '1:523719868125:android:1505e4ae78d6c781026534',
    messagingSenderId: '523719868125',
    projectId: 'blooddonation-f9c79',
    storageBucket: 'blooddonation-f9c79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6dAdBk1-JxO-3CU1MhAGMBtwBoj_v4oE',
    appId: '1:523719868125:ios:7ce77614a8d00ae8026534',
    messagingSenderId: '523719868125',
    projectId: 'blooddonation-f9c79',
    storageBucket: 'blooddonation-f9c79.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6dAdBk1-JxO-3CU1MhAGMBtwBoj_v4oE',
    appId: '1:523719868125:ios:9debd599f47e823e026534',
    messagingSenderId: '523719868125',
    projectId: 'blooddonation-f9c79',
    storageBucket: 'blooddonation-f9c79.appspot.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
